# NOTE this file follows version 2 of docker-compose file format
#
# Example usage 
# To build image of web and start 3 containers (-d is for detached deamon mode)
#  docker-compose up -d
# NOTE above builds an image expdockercompose1_web, 
#      then starts 3 containers using images; jwilder/nginx-proxy, expdockercompose1_web, redis
#      Afterwards you can hit it via below and it will return count of hits and the host name serving hit
#  curl 0.0.0.0  
#  
# To see containers running
#   docker ps
#
# To see docker compose started containers running
#   docker-compose ps
#
# To see logs while 3 containers are running
#  docker-compose logs
#
# To increase number of web containers to 5
#  docker-compose scale web=5
# then hit with curl and watch the logs, look how many web containers are running and returned host name to curl
#
# To decrease number of web containers to 2
#  docker-compose scale web=2
# and watch the web containers reducing from 5 to 2 (watch via docker-compose ps) and in logs and in curl returned host name
#
# To stop them(all 3 containers above started)
#  docker-compose down
#
version: '2'
services:
  web:
    build: .
    volumes:
     - .:/code
    links:
     - redis
    expose:
     - "5000"
    environment:
     - VIRTUAL_HOST=0.0.0.0
  redis:
    image: redis
  lb:
    image: jwilder/nginx-proxy
    links:
     - web
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
     - "80:80"
